name: Events Demo 1
on:
  pull_request:
    types:
      - opened
    branches:
      - main 
      - dev
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
      - '.github/workflows/demo1.yml'
# env:
#   sample_user: 'demo1'
#   sample_password: 'demo123'
jobs:
  deploy:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: echo the value of the env sec named user
        run: echo "The value of SAMPLE_USER is ${{ secrets.SAMPLE_USER }}"
      - name: echo the value of the env sec named password
        run: echo "The value of SAMPLE_PASSWORD is ${{ secrets.SAMPLE_PASSWORD }}"
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."